apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
spec:
  selector:
    matchLabels:
      app: pi-hole
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      hostNetwork: true
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
      containers:
        - name: pi-hole
          image: pihole/pihole:latest
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 67
              protocol: UDP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          env:
            - name: TZ
              value: America/Fortaleza
            - name: WEBPASSWORD
              value: 123
            - name: VIRTUAL_HOST
              value: your.domain
          volumeMounts:
            - name: etc
              mountPath: /etc/pihole
            - name: dnsmasq
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: etc
          hostPath:
            path: /home/pi/apps/pi-hole/etc
            type: Directory
        - name: dnsmasq
          hostPath:
            path: /home/pi/apps/pi-hole/dnsmasq.d
            type: Directory
